@startuml
'https://plantuml.com/object-diagram

package api

package service

package infra

package application

package domain

api --> service

service --> application

domain --> service

domain --> infra

infra --> application



@enduml
