name: Pages

on:
  push:
    branches:
      - master # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm i -S hexo-prism-plugin -g
          npm install hexo-generator-search --save -g
          npm i hexo-permalink-pinyin  -g
          npm i --save hexo-wordcount -g
          npm install hexo-filter-github-emojis  -g
          npm install hexo-generator-feed  -g
          npm install hexo-theme-next --save -g
          npm install
      - name: Build
        run: |
          hexo clean
          hexo generate
          hexo deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public