name: Pages

on:
  push:
    branches:
      - master # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install hexo-generator-search --save -g
          npm install hexo-theme-next --save -g
          npm install --save hexo-helper-live2d -g
          npm install live2d-widget-model-z16 -g
          npm install hexo-abbrlink --save -g
          npm install hexo-neat --save -g
          npm install hexo-baidu-url-submit -g
          npm install hexo-submit-urls-to-search-engine --save -g
          npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public